### ISSUE TITLE
Perma.cc API key not being recognized

### ISSUE THREAD

**Issue by griffey** [berkmancenter/amber_wordpress#24]
With the 1.4 public release, I'm attempting to add my Perma.cc API key to enable perma as an option, but the plugin is refusing to recognize it...I add it to the field, click save, and get an error that says "Perma.cc API key is required...."
<img width="485" alt="screen shot 2016-01-28 at 3 00 01 pm" src="https://cloud.githubusercontent.com/assets/220018/12657156/eb9558a4-c5cf-11e5-8ab6-47181c412901.png">

**Comment by jlicht** [comment]
Did you ever have a previous version of the plugin installed?

There are two configuration settings on that page (Perma URL and Perma API URL) that were visible in previous versions of the plugin but are now hidden from the end user via CSS. If either of those were empty (perhaps because they were unset when using a previous version of the plugin?), you would see the error message you describe.

**Comment by griffey** [comment]
I did have the 1.2 installed, yes, but deleted the plugin prior to the install of the 1.4...

Given that this is the issue, what's the fix?

**Comment by jlicht** [comment]
It's a complete hack, but you go to the Amber Settings page and run ```jQuery(".form-table tr").show()``` in the javascript console, all possible fields will be displayed. 

Then update the Perma fields:

**Perma URL:** http://perma.cc
**Perma API URL:** https://api.perma.cc

Save your settings, and you should be all set.

**Comment by griffey** [comment]
Seems to have fixed it. Still playing with the other functionality, but that go rid of the error. 

Thanks!
