### ISSUE TITLE
Only include extra CSS and Javascript if needed

### ISSUE THREAD

**Issue by vasilisvg** [berkmancenter/amber_wordpress#31]
I noticed that a CSS file and a Javascript file were added to the head of my blog. I understand they are needed if you want to show an overlay on `:hover` or click, but when you deselect those options these extra requests don't seem necessary.

**Comment by jlicht** [comment]
The plugin modifies pages served by the site in two ways - in addition to embedding CSS and Javascript, it also rewrites cached links to have additional attributes ( `data-versionurl`,  `data-versiondate`, and `data-amber-behavior`). 

Can you tell us a bit more about the use case for disabling the hover/popup behavior for all links? Since in this scenario users of your site won't have access to any of the snapshots created by Amber, I'm wondering if it would make sense to disable the link rewriting as well.

**Comment by vasilisvg** [comment]
I would assume that the plugin would work like this when you disable the hover/popup option:

1. If a visitor clicks on a link they should see the page at its original URL if it still exists. 
2. If it doesn't exist and there's a cached version of it, it should get to see the cached version immediately

This way there's no extra action required by the visitor. They click a link, they get a page. And this also means that there's no need for extra scripts and CSS files. This can all be done on the server.

**Comment by jlicht** [comment]
For what it's work, you can get this behavior by selecting the "Link directly to Snapshot" option in the settings (Amber Delivery -> Unavailable links). However, this is all currently all handled by the client-side javascript/CSS, so those files would still need to be loaded.

**Comment by vasilisvg** [comment]
In that case I can understand that the javascript file needs to be included on pages where links are replaced. But can you explain why the CSS file is needed for this option? 
Would it be possible to only include these javascript and CSS files on pages where they are really needed?

**Comment by jlicht** [comment]
To summarize:

* In the scenario where there are no popups or javascript configured, we could remove the dependency on including the CSS file.
* In the scenario where no end-user actions at all are desired, we could (a) remove the dependency on the CSS and JavaScript, and (b) remove annotations on the links.
